// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_AuthenticateUser_FullMethodName = "/AuthenticationService.UserService/AuthenticateUser"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	AuthenticateUser(ctx context.Context, opts ...grpc.CallOption) (UserService_AuthenticateUserClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AuthenticateUser(ctx context.Context, opts ...grpc.CallOption) (UserService_AuthenticateUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_AuthenticateUser_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceAuthenticateUserClient{stream}
	return x, nil
}

type UserService_AuthenticateUserClient interface {
	Send(*UserWithTokenRequest) error
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceAuthenticateUserClient struct {
	grpc.ClientStream
}

func (x *userServiceAuthenticateUserClient) Send(m *UserWithTokenRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceAuthenticateUserClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	AuthenticateUser(UserService_AuthenticateUserServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) AuthenticateUser(UserService_AuthenticateUserServer) error {
	return status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_AuthenticateUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).AuthenticateUser(&userServiceAuthenticateUserServer{stream})
}

type UserService_AuthenticateUserServer interface {
	Send(*UserResponse) error
	Recv() (*UserWithTokenRequest, error)
	grpc.ServerStream
}

type userServiceAuthenticateUserServer struct {
	grpc.ServerStream
}

func (x *userServiceAuthenticateUserServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceAuthenticateUserServer) Recv() (*UserWithTokenRequest, error) {
	m := new(UserWithTokenRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthenticationService.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuthenticateUser",
			Handler:       _UserService_AuthenticateUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
